CL.TMS.Web/Areas/Collector/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Script.Serialization;
using System.Text;

using CL.TMS.UI.Common.UserInterface;
using CL.TMS.Common;
using CL.TMS.UI.Common;
using CL.TMS.DataContracts.ViewModel.Transaction;
using CL.TMS.ServiceContracts.RegistrantServices;
using CL.TMS.ServiceContracts.SystemServices;
using CL.TMS.Security.Authorization;
using CL.TMS.Web.Infrastructure;
using CL.TMS.Resources;
using CL.TMS.DataContracts.ViewModel.Common.FileUpload;
using CL.TMS.DataContracts.ViewModel.Common;
using CL.TMS.Configuration;

using Newtonsoft.Json;
using CL.TMS.DataContracts.ViewModel.Transaction.Collector;
using CL.TMS.Common.Enum;
using CL.TMS.Framework.DTO;
using CL.TMS.Security;
using CL.TMS.UI.Common.Security;

namespace CL.TMS.Web.Areas.Collector.Controllers
{
    public class TransactionController : BaseController
    {
        #region Properties
        private ITransactionService transactionService;
        private IRegistrantService registrantService;
        private IClaimService claimService;
        #endregion


        #region Constructor
        public TransactionController(ITransactionService transactionService, IRegistrantService registrantService, IClaimService claimService)
        {
            this.transactionService = transactionService;
            this.registrantService = registrantService;
            this.claimService = claimService;
        }
        #endregion


        #region Action Methods
        public ActionResult Index(int id, string type, int direction)
        {
            ViewBag.ngApp = "TransactionApp";
            ViewBag.VendorCode = TreadMarksConstants.Collector;

            var claimStatus = this.claimService.GetClaimStatus(id);

            ViewBag.ClaimId = id;
            ViewBag.TypeId = type;
            ViewBag.Direction = direction;

            if (null != SecurityContextHelper.CurrentVendor)
            {
                ViewBag.RegistrationNumber = SecurityContextHelper.CurrentVendor.RegistrationNumber;
                ViewBag.BusinessName = SecurityContextHelper.CurrentVendor.BusinessName;

                var vendorReference = claimService.GetVendorReference(id);
                if (SecurityContextHelper.CurrentVendor.VendorId != vendorReference.VendorId || vendorReference.VendorType != 2)
                {
                    if (SecurityContextHelper.IsValidVendorContext(vendorReference.VendorId))
                    {
                        return RedirectToAction("EmptyPage", "Common", new { area = "System", navigationAction = "loadTopMenu" });
                    }
                    else
                    {
                        return RedirectToAction("UnauthorizedPage", "Common", new { area = "System" });
                    }
                }
            }
            else
            {
                return RedirectToAction("EmptyPage", "Common", new { area = "System" });
            }

            ViewBag.AllowInternalNote = SecurityContextHelper.IsStaff();
            ViewBag.AllowTransactionHandling = (SecurityContextHelper.IsStaff() && claimStatus == ClaimStatus.UnderReview);

            //OTSTM2-155
            bool bWritePermission = (ResourceActionAuthorizationHandler.CheckUserSecurity(TreadMarksConstants.ClaimsCollectorClaimSummaryOutbound) == SecurityResultType.EditSave);
            if (SecurityContextHelper.IsStaff()) ViewBag.AllowAddTransaction = this.claimService.IsClaimAllowAddNewTransaction(id) && bWritePermission;
            else ViewBag.AllowAddTransaction = ((bWritePermission && claimStatus == ClaimStatus.Open));

            ViewBag.ClaimPeriod = this.claimService.GetClaimPeriod(id).ShortName;
            ViewBag.AllowEdit = bWritePermission;

            switch (type)
            {
                case TreadMarksConstants.TCR:
                    ViewBag.TransactionType = TreadMarksConstants.TCR;
                    ViewBag.HeaderName = "TCR Transactions";
                    return View("TCRTransactions");

                case TreadMarksConstants.DOT:
                    ViewBag.TransactionType = TreadMarksConstants.DOT;
                    ViewBag.HeaderName = "DOT Transactions";
                    return View("DOTTransactions");

                default:
                    return RedirectToAction("Index", "Claims", new { area = "Collector" });
            };
        }
        #endregion


        #region Service Methods

        #region Paper Form Service Methods
        [HttpPost]
        public NewtonSoftJsonResult initializePaperForm(int id, string type, int direction)
        {
            var claimPeriod = this.claimService.GetClaimPeriod(id);

            ICollectorTransactionViewModel paperFormModel = new CollectorTransactionViewModel();

            switch (type)
            {
                case TreadMarksConstants.TCR:
                    paperFormModel = new CollectorTCRTransactionViewModel();
                    paperFormModel.initialize();
                    paperFormModel.TireTypeList.AddRange(TransactionHelper.GetTransactionTireTypeViewModelList(TransactionHelper.GetAvailableTireTypeListTireTypeList(TreadMarksConstants.TCR)));
                    break;

                case TreadMarksConstants.DOT:
                    paperFormModel = new CollectorDOTTransactionViewModel();
                    paperFormModel.initialize();
                    paperFormModel.TireTypeList.AddRange(TransactionHelper.GetTransactionTireTypeViewModelList(TransactionHelper.GetAvailableTireTypeListTireTypeList(TreadMarksConstants.DOT)));
                    break;

                default:
                    return new NewtonSoftJsonResult { Data = new { status = false, statusMsg = MessageResource.InvalidData } };
            };

            paperFormModel.CurrentVendorId = SecurityContextHelper.CurrentVendor.VendorId;
            paperFormModel.ClaimId = id;
            paperFormModel.IsAutoDismantler = string.Equals(SecurityContextHelper.CurrentVendor.PrimaryBusinessActivity, "Auto dismantler", StringComparison.OrdinalIgnoreCase);

            // Form date related setting    
            TransactionHelper.initializeFormDate(paperFormModel.FormDate, claimPeriod, ResourceActionAuthorizationHandler.CheckUserSecurity(TreadMarksConstants.ClaimsCollectorClaimSummary));
            paperFormModel.FormDate.DisabledDateRangeList = new List<TransactionDisabledDateRangeViewModel>();
            paperFormModel.FormDate.DisabledDateRangeList.AddRange(transactionService.GetVendorInactiveDateRanges(SecurityContextHelper.CurrentVendor.VendorId));


            return new NewtonSoftJsonResult { Data = new { status = true, statusMsg = MessageResource.ValidData, data = paperFormModel } };
        }

        [HttpPost]
        public NewtonSoftJsonResult AddPaperTransactionTCR(CollectorTCRTransactionViewModel transactionDataModel)
        {
            try
            {
                if (!ModelState.IsValid) return new NewtonSoftJsonResult { Data = new { status = false, errorType = "invalid-model" } };
                if (transactionDataModel.CurrentVendorId != SecurityContextHelper.CurrentVendor.VendorId) return new NewtonSoftJsonResult { Data = new { status = false, errorType = "invalid-vendor-context" } };

                transactionDataModel.Inbound = registrantService.GetVendorByNumber(transactionDataModel.HaulerNumber.ToString());
                transactionDataModel.Outbound = SecurityContextHelper.CurrentVendor;

                var creationNotification = transactionService.AddCollectorPapeFormTransaction(transactionDataModel);

                if (transactionDataModel.Inbound != null) TransactionCommonHelper.SendAddTransactionEmailNotification(creationNotification);

                return new NewtonSoftJsonResult { Data = new { status = true, errorType = "" } };
            }
            catch (Exception ex)
            {

                return new NewtonSoftJsonResult { Data = new { status = false, errorType = "save-error" } };
            }
        }

        [HttpPost]
        public NewtonSoftJsonResult AddPaperTransactionDOT(CollectorDOTTransactionViewModel transactionDataModel)
        {
            try
            {
                if (!ModelState.IsValid) return new NewtonSoftJsonResult { Data = new { status = false, errorType = "invalid-model" } };
                if (transactionDataModel.CurrentVendorId != SecurityContextHelper.CurrentVendor.VendorId) return new NewtonSoftJsonResult { Data = new { status = false, errorType = "invalid-vendor-context" } };

                transactionDataModel.Inbound = registrantService.GetVendorByNumber(transactionDataModel.HaulerNumber.ToString());
                transactionDataModel.Outbound = SecurityContextHelper.CurrentVendor;

                var creationNotification = transactionService.AddCollectorPapeFormTransaction(transactionDataModel);

                if (transactionDataModel.Inbound != null) TransactionCommonHelper.SendAddTransactionEmailNotification(creationNotification);

                return new NewtonSoftJsonResult { Data = new { status = true, errorType = "" } };
            }
            catch (Exception ex)
            {
                return new NewtonSoftJsonResult { Data = new { status = false, errorType = "save-error" } };
            }
        }
        #endregion

        #region List Handler Service Methods
        public ActionResult GetTransactionListHandler(DataGridModelExtend param)
        {
            if (SecurityContextHelper.CurrentVendor != null)
            {
                var vendor = SecurityContextHelper.CurrentVendor;

                if (vendor.IsVendor)
                {
                    string transactionType = param.DataType;

                    var searchText = param.Search != null && param.Search.ContainsKey("value")
                         ? param.Search["value"].Trim()
                         : string.Empty;

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerCommonTemplates.cshtml
@Html.Partial("_TransactionFormDatePickerTemplate")
@Html.Partial("_TransactionFormNumberTemplate")
@Html.Partial("_TransactionVendorInformationTemplate")
@Html.Partial("_TransactionTireTypeCountTemplate")
@Html.Partial("_TransactionSupportingDocumentTemplate")
@Html.Partial("_TransactionDocumentUploaderTemplate")
@Html.Partial("_TransactionInternalNoteTemplate")

@Html.Partial("_TransactionScaleTicketTemplate")
@Html.Partial("_PTRDisplayVarianceTemplate")
@Html.Partial("_TransactionUnregisteredCompanyTemplate")
@Html.Partial("_UCRPaymentEligibleTemplate")
@Html.Partial("_STCEventNumberTemplate")
@Html.Partial("_TransactionInvoiceNumberTemplate")
@Html.Partial("_RTRTireMarketTemplate")

@Html.Partial("_TransactionSubmitConfirmTemplate")
@Html.Partial("_TransactionCancelConfirmTemplate")

@Html.Partial("_HaulerTrasactionHandlerTemplate")
@Html.Partial("_TransactionViewAdjustmentDetailTemplate")
@Html.Partial("_TransactionViewTCRTemplate")
@Html.Partial("_TransactionViewDOTTemplate")
@Html.Partial("_TransactionViewUCRTemplate")
@Html.Partial("_TransactionViewHITTemplate")
@Html.Partial("_TransactionViewSTCTemplate")
@Html.Partial("_TransactionViewPTRTemplate")
@Html.Partial("_TransactionViewRTRTemplate")

@Html.Partial("_TransactionAdjustmentToggleTemplate")
@Html.Partial("_TransactionAdjustmentTCRTemplate")
@Html.Partial("_TransactionAdjustmentDOTTemplate")
@Html.Partial("_TransactionAdjustmentHITTemplate")
@Html.Partial("_TransactionAdjustmentPTRTemplate")
@Html.Partial("_TransactionAdjustmentSTCTemplate")
@Html.Partial("_TransactionAdjustmentUCRTemplate")
@Html.Partial("_TransactionAdjustmentRTRTemplate")

@Html.Partial("_TransactionReviewToolbarTemplate")
@Html.Partial("_TransactionHandlerHeaderTemplate")
@Html.Partial("_TransactionHandlerWorkflowTemplate")
@Html.Partial("_TransactionViewDateDisplayTemplate")
@Html.Partial("_TransactionViewParticipantInfoTemplate")
@Html.Partial("_TransactionViewTireTypeCountTemplate")
@Html.Partial("_TransactionViewScaleTicketTemplate")
@Html.Partial("_TransactionViewPaperScaleTicketTemplate")
@Html.Partial("_TransactionViewSupportingDocumentTemplate")
@Html.Partial("_TransactionViewPhotoTemplate")
@Html.Partial("_TransactionViewCommentTemplate")
@Html.Partial("_TransactionViewSignatureTemplate")
@Html.Partial("_TransactionManageInternalNoteTemplate")

@Html.Partial("_TransactionAdjustSupportingDocumentAttachmentTemplate")
@Html.Partial("_TransactionCreationStatusMessageTemplate")

@*OTSTM2-148*@
@Html.Partial("_TransactionViewMobileSupportingDocTemplate")
@*OTSTM2-148*@

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerHeader.cshtml
@using CL.TMS.Resources
@using CL.TMS.Common
@using CL.TMS.Security.Authorization

<!-- Component: Transactions Header -->
<div id="fixedClaimHeader" class="row comp-claims-header fixed-claim-header">
    <div class="col-xs-7 col-sm-6">
        <h2 class="fixed-claim-header-title">@ViewBag.HeaderName</h2>
        <div class="btn-group fixed-claim-header-period-btn-group">
            <a class="btn btn-warning" href="@Url.Action("ClaimSummary", "Claims", new { area = "Hauler", claimId = @ViewBag.ClaimId })"><i class=" fa fa-chevron-left"></i> Claim Summary</a>
            <a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="fa fa-caret-down"></span>
            </a>
            <ul class="dropdown-menu">
                <li class="li-label">Inbound</li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.TCR, direction = 1 })"><i class="fa fa-file-text-o"></i> TCR</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.DOT, direction = 1 })"><i class="fa fa-file-text-o"></i> DOT</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.UCR, direction = 1 })"><i class="fa fa-file-text-o"></i> UCR</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.HIT, direction = 1 })"><i class="fa fa-file-text-o"></i> HIT</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.STC, direction = 1 })"><i class="fa fa-file-text-o"></i> STC</a></li>
                <li class="divider"></li>
                <li class="li-label">Outbound</li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.PTR, direction = 2 })"><i class="fa fa-file-text-o"></i> PTR</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.HIT, direction = 2 })"><i class="fa fa-file-text-o"></i> HIT</a></li>
                <li><a href="@Url.Action("Index", "Transaction", new { area = "Hauler", id = @ViewBag.ClaimId, type = TreadMarksConstants.RTR, direction = 2 })"><i class="fa fa-file-text-o"></i> RTR</a></li>
            </ul>
        </div>    
        @if (null != SecurityContextHelper.CurrentVendor)
        {
            if (SecurityContextHelper.IsParticipant())
            {
                <div class="sub-header-claimdate fixed-claim-header-claimdate-participant">@ViewBag.ClaimPeriod</div>
            }
        }
    </div>
    @*<div class="col-xs-5 col-sm-6">
        <div class="sub-header-registrantinfo">@ViewBag.RegistrationNumber</div>
        <div class="sub-header-companyname">@ViewBag.BusinessName</div>
    </div>*@
    @if (null != SecurityContextHelper.CurrentVendor)
    {
        if (SecurityContextHelper.IsStaff())
        {
            <div class="col-xs-5 col-sm-6">
                @Html.Partial("_ParticipantHeader", SecurityContextHelper.CurrentVendor)
            </div>
        }
        else
        {
            <div class="col-xs-5 col-sm-6">
                <div class="sub-header-registrantinfo fixed-claim-header-registrantinfo">@SecurityContextHelper.CurrentVendor.RegistrationNumber</div>
            </div>
            @*<div class="col-xs-5 col-sm-6">
                <div class="sub-header-claimdate fixed-claim-header-participant-claimdate">@ViewBag.ClaimPeriod</div>
            </div>*@
        }
    }
</div>
@if (SecurityContextHelper.IsStaff())
{ 
    @Html.Partial("_TransactionActivityStaff")
}
<!-- /Component: Transactions Header -->

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerPaperFormDOTTemplate.cshtml
@using CL.TMS.Resources

<script type="text/ng-template" id="paper-form.html">
    <div class="comp-all-modal">
        <form id="transForm" name="transForm">
            <div class="modal-header">
                <button type="button" ng-click="cancelPaperForm()" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title" align="center">DOT Paper Form</h3>
            </div>
            <div class="modal-body padding-25">
                <creation-status-message ng-if="statusModel.display" status-model="statusModel"></creation-status-message>

                <div class="row">
                    <div class="col-sm-3">
                        <form-date-picker label-text="Date Collected" form="transForm" form-date="trans.formDate"></form-date-picker>
                    </div>
                    <div class="col-md-3">
                        <form-number-collector form="transForm" claim-id={{trans.claimId}} form-type="DOT" form-number="trans.formNumber"></form-number-collector>
                    </div>
                    <div class="col-md-6">
                        <vendor-information-collector form="transForm" transaction-date="trans.formDate" vendor-code="Collector" vendor-number="trans.collectorNumber"></vendor-information-collector>
                    </div>                    
                </div>
                <div class="row">  
                    <div class="col-md-6" dot-scale-ticket-handler>
                        <br /><br />
                        <scale-ticket-collector form="transForm" scale-ticket="trans.scaleTicket" mandatory="{{'false'}}"></scale-ticket-collector>
                    </div>           
                    <div class="col-md-6">
                        <tire-type-count form="transForm" tire-type-list="trans.tireTypeList" generate-tires="trans.generateTires"></tire-type-count>
                    </div>
                </div>                    

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <supporting-document-selector list="trans.supportingDocumentList"></supporting-document-selector>
                    </div>
                </div>                

                <document-uploader transaction-id="{{trans.transactionId}}" upload-list="trans.uploadDocumentList" is-required="documentUploadRequired"></document-uploader>                               

                @if (@ViewBag.AllowInternalNote)
                { 
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <internal-note-collector form="transForm" internal-note="trans.internalNote"></internal-note-collector>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-danger btn-lg" ng-click="cancelPaperForm()">
                    <i class="glyphicon fa fa-ban" aria-hidden="true"></i>
                    @UIResource.Cancel
                </button>
                <button type="button" class="btn btn-success btn-lg" ng-click="submitPaperForm()">
                    <i class="glyphicon fa fa-floppy-o" aria-hidden="true"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</script>

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerPaperFormHITTemplate.cshtml
@using CL.TMS.Resources

<script type="text/ng-template" id="paper-form.html">
    <div class="comp-all-modal">
        <form id="transForm" name="transForm">
            <div class="modal-header">
                <button type="button" ng-click="cancelPaperForm()" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title" align="center">HIT Paper Form</h3>
            </div>
            <div class="modal-body padding-25">
                <creation-status-message ng-if="statusModel.display" status-model="statusModel"></creation-status-message>

                <div class="row">
                    <div class="col-sm-3">
                        <form-date-picker label-text="Date Collected" form="transForm" form-date="trans.formDate"></form-date-picker>
                    </div>
                    <div class="col-md-3">
                        <form-number-collector form="transForm" claim-id={{trans.claimId}} form-type="HIT" form-number="trans.formNumber"></form-number-collector>
                    </div>
                    <div class="col-md-6">
                        <vendor-information-collector form="transForm" transaction-date="trans.formDate" vendor-code="Hauler" vendor-number="trans.haulerNumber"></vendor-information-collector>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <tire-type-count form="transForm" tire-type-list="trans.tireTypeList"></tire-type-count>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <supporting-document-selector list="trans.supportingDocumentList"></supporting-document-selector>
                    </div>
                </div>

                <document-uploader transaction-id="{{trans.transactionId}}" upload-list="trans.uploadDocumentList" is-required="documentUploadRequired"></document-uploader>

                @if (@ViewBag.AllowInternalNote)
                {
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <internal-note-collector form="transForm" internal-note="trans.internalNote"></internal-note-collector>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-danger btn-lg" data-dismiss="modal" ng-click="cancelPaperForm()">
                    <i class="glyphicon fa fa-ban" aria-hidden="true"></i>
                    @UIResource.Cancel
                </button>
                <button type="button" class="btn btn-success btn-lg" ng-click="submitPaperForm()">
                    <i class="glyphicon fa fa-floppy-o" aria-hidden="true"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</script>

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerPaperFormPTRTemplate.cshtml
@using CL.TMS.Resources

<script type="text/ng-template" id="paper-form.html">
    <div class="comp-all-modal">
        <form id="transForm" name="transForm">
            <div class="modal-header">
                <button type="button" ng-click="cancelPaperForm()" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title" align="center">Add PTR Paper Form</h3>
            </div>
            <div class="modal-body padding-25">
                <creation-status-message ng-if="statusModel.display" status-model="statusModel"></creation-status-message>

                <div class="row">
                    <div class="col-sm-3">
                        <form-date-picker label-text="Date Delivered" form="transForm" form-date="trans.formDate"></form-date-picker>
                    </div>
                    <div class="col-md-3">
                        <form-number-collector form="transForm" claim-id={{trans.claimId}} form-type="PTR" form-number="trans.formNumber"></form-number-collector>
                    </div>
                    <div class="col-md-6">
                        <vendor-information-collector form="transForm" transaction-date="trans.formDate" vendor-code="Processor" vendor-number="trans.processorNumber"></vendor-information-collector>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-6">
                        <scale-ticket-collector form="transForm" scale-ticket="trans.scaleTicket" mandatory="{{'true'}}"></scale-ticket-collector>
                    </div>

                    <div class="col-md-3">
                        <ptr-display-variance></ptr-display-variance>
                    </div>

                    <div class="col-md-3">&nbsp;</div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <tire-type-count form="transForm" tire-type-list="trans.tireTypeList"></tire-type-count>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <supporting-document-selector list="trans.supportingDocumentList"></supporting-document-selector>
                    </div>
                </div>

                <document-uploader transaction-id="{{trans.transactionId}}" upload-list="trans.uploadDocumentList" is-required="documentUploadRequired"></document-uploader>

                @if (@ViewBag.AllowInternalNote)
                {
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <internal-note-collector form="transForm" internal-note="trans.internalNote"></internal-note-collector>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-danger btn-lg" data-dismiss="modal" ng-click="cancelPaperForm()">
                    <i class="glyphicon fa fa-ban" aria-hidden="true"></i>
                    @UIResource.Cancel
                </button>
                <button type="button" class="btn btn-success btn-lg" ng-click="submitPaperForm()">
                    <i class="glyphicon fa fa-floppy-o" aria-hidden="true"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</script>

CL.TMS.Web/Views/Shared/Transaction/Hauler/_HaulerPaperFormSTCTemplate.cshtml
@using CL.TMS.Resources

<script type="text/ng-template" id="paper-form.html">
    <div class="comp-all-modal">
        <form id="transForm" name="transForm">
            <div class="modal-header">
                <button type="button" ng-click="cancelPaperForm()" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h3 class="modal-title" align="center">STC Paper Form</h3>
            </div>
            <div class="modal-body padding-25">
                <creation-status-message ng-if="statusModel.display" status-model="statusModel"></creation-status-message>

                <div class="row">
                    <div class="col-sm-3">
                        <form-date-picker label-text="Date Collected" form="transForm" form-date="trans.formDate"></form-date-picker>
                    </div>
                    <div class="col-md-4">
                        <form-number-collector form="transForm" claim-id={{trans.claimId}} form-type="STC" form-number="trans.formNumber"></form-number-collector>
                    </div>
                    <div class="col-md-4">
                        <stc-event-number-collector form="transForm" event-number="trans.eventNumber" event-number-validation-condition="eventNumberValidationCondition" date-collected="trans.formDate"></stc-event-number-collector> <!--OTSTM2-1214--><!--OTSTM2-1215 date-collected-->
                    </div>
                </div>

                <unregistered-company-collector form="transForm" company-info="trans.companyInfo" company-label-text="{{'Group / Individual Name'}}" country-list="[]"></unregistered-company-collector>
                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <tire-type-count form="transForm" tire-type-list="trans.tireTypeList"></tire-type-count>
                    </div>
                </div>

                <hr>

                <div class="row">
                    <div class="col-md-12">
                        <supporting-document-selector list="trans.supportingDocumentList"></supporting-document-selector>
                    </div>
                </div>

                <document-uploader transaction-id="{{trans.transactionId}}" upload-list="trans.uploadDocumentList" is-required="documentUploadRequired"></document-uploader>

                @if (@ViewBag.AllowInternalNote)
                {
                    <hr>
                    <div class="row">
                        <div class="col-md-12">
                            <internal-note-collector form="transForm" internal-note="trans.internalNote"></internal-note-collector>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="reset" class="btn btn-danger btn-lg" ng-click="cancelPaperForm()">
                    <i class="glyphicon fa fa-ban" aria-hidden="true"></i>
                    @UIResource.Cancel
                </button>
                <button type="button" class="btn btn-success btn-lg" ng-click="submitPaperForm()">
                    <i class="glyphicon fa fa-floppy-o" aria-hidden="true"></i>
                    Save
                </button>
            </div>
        </form>
    </div>
</script>